#wrt a pro t input eight number from the user and display all the unique number (once)

s = set()
n = input("Enter number1:")
s.add(int(n))
n = input("Enter number1:")
s.add(int(n))
n = input("Enter number1:")
s.add(int(n))
n = input("Enter number1:")
s.add(int(n))
n = input("Enter number1:")
s.add(int(n))
n = input("Enter number1:")
s.add(int(n))
n = input("Enter number1:")
s.add(int(n))
n = input("Enter number1:")
s.add(int(n))
n = input("Enter number1:")
s.add(int(n))

print(s)
